name: 'Terraform CI'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-opa:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2



    - name: Run OPA Tests 
      run: conftest test -d policy/ tfplan.json

  terraform-plan:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: checkout source code
      uses: actions/checkout@v2

    - name: setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7

    - name: setup opa
      uses: open-policy-agent/setup-opa@v1
      with:
        version: latest

    - name: setup conftest
      uses: instrumenta/conftest-action@master
    
    - name: terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: terraform init
      id: init
      run: terraform init

    - name: terraform validate
      id: validate
      run: terraform validate -no-color

    - name: terraform plan
      id: plan
      run: terraform plan --out tfplan.binary

    - name: terraform show
      run: terraform show -json tfplan.binary > tfplan.json

    - name: run opa tests
      run: conftest test -d policy/ tfplan.json