name: 'Terraform CI'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform-plan:
    name: 'terraform format & plan'
    runs-on: macos-latest

    steps:
    - name: checkout source code
      uses: actions/checkout@v2

    - name: setup terraform
      uses: hashicorp/setup-terraform@v2

    - name: setup opa
      uses: open-policy-agent/setup-opa@v1
      with:
        version: latest
    
    - name: terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: terraform init
      id: init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}

    - name: terraform validate
      id: validate
      run: terraform validate -no-color

    - name: terraform plan
      id: plan
      run: terraform plan --out tfplan.binary
      env:
        GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_CREDENTIALS}}

    - name: terraform show
      id: show
      run: terraform show -json tfplan.binary > tfplan.json

    - name: terraform cat
      id: cat
      run: cat tfplan.json 

    - name: install conftest
      run: |
        LATEST_VERSION=$(wget -O - "https://api.github.com/repos/open-policy-agent/conftest/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c 2-)
        wget "https://github.com/open-policy-agent/conftest/releases/download/v${LATEST_VERSION}/conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz"
        tar xzf conftest_${LATEST_VERSION}_Linux_x86_64.tar.gz
        sudo mv conftest /usr/local/bin
    
    - name: run opa
      run: conftest test -o "stdout" -p "policy" --namespace "main" tfplan.json 